<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>maude</string>
	</array>
	<key>name</key>
	<string>MaudeSyntax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#everything</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(fmod) (.+) (is)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(endfm)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>name</key>
			<string>module</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>everything</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A comment</string>
					<key>match</key>
					<string>\*\*\*.*</string>
					<key>name</key>
					<string>comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(pr|protecting) (.+) \.</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>keywords</string>
					<key>match</key>
					<string>(ops|op|vars|var|sorts|sort|subsorts|subsort|set|trace)</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on|off)</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Sorts</string>
					<key>match</key>
					<string>[A-Z][a-z]+</string>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.deleted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(eq|ceq) ([^=]+) = (.+) \.</string>
					<key>name</key>
					<string>equation</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.maude</string>
	<key>uuid</key>
	<string>d9f1b179-4829-45ea-9bb7-b20c447fc9ef</string>
</dict>
</plist>
